PROJECT := main
SEARCH :=
HEADERS := Circle.hpp factory.hpp operators.hpp Picture.hpp Rectangle.hpp screen_object.hpp custom_execptions.hpp
SOURCES := Circle.cpp factory.cpp operators.cpp Picture.cpp Rectangle.cpp screen_object.cpp
TARGET := native
RUN_PAUSE := echo "Run completed"
PROJECT_CPP_FLAGS += -fexceptions
include $(HWLIB)/makefile.inc
