PROJECT := main
SEARCH :=
HEADERS := board_builder.hpp comand_line_interface.hpp game_interface.hpp game_logic.hpp graphical_user_interface.hpp game_moves.hpp game_data.hpp terminal_game_setup.hpp
SOURCES := board_builder.cpp comand_line_interface.cpp game_logic.cpp graphical_user_interface.cpp game_moves.cpp terminal_game_setup.cpp
TARGET := native
RUN_PAUSE := echo "Run completed"
PROJECT_CPP_FLAGS += -fexceptions
include $(HWLIB)/makefile.inc
